### ISSUE TITLE
Build error on ubuntu 16.04

### ISSUE THREAD

**Issue by delmottea** [InteractiveComputerGraphics/PositionBasedDynamics#37]
Hello,
The code doesn't compile on Ubuntu 16.04, with cmake version 3.5.1, g++ 5.4.0.

Lot of errors like :
SPlisHSPlasH-master/extern/PositionBasedDynamics/src/ExternalProject_PositionBasedDynamics/Common/Common.h:24:8: error: expected nested-name-specifier before ‘Vector2r’
  using Vector2r = Eigen::Matrix<Real, 2, 1>;

I solved it by adding 
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fopenmp")
in CMakeLists.txt

Same problem in SPlisHSPlasH project

**Comment by louen** [comment]
I think the correct way to do this portably for all supported compilers with CMake is to add this instruction 
```cmake
    set(CMAKE_CXX_STANDARD 11)
```
which was added by commit 1bec309 to `Common.cmake`.

This should direct cmake  to add the correct`-std` option. Maybe you need to add it to the Splishsplash project's cmake as well ?

**Comment by janbender** [comment]
Thanks for pointing this out. I will add the Cmake instruction in SPlisHSPlasH as well.
